/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package serialcodegenerator3;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author pooqw
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();

        jTabbedPane.setIconAt(0, new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_password_70px.png")));
        jTabbedPane.setIconAt(1, new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_table_properties_50px.png")));
        jTabbedPane.setIconAt(2, new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_time_span_50px.png")));
        
        EndingDateChooser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Date_Span_20px_1.png")));
        StartingDateChooser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Date_Span_20px_1.png")));
        FilePathCorrect.setVisible(false);
        SerialCodeCorrect.setVisible(false);

        SymbolNum.setValue(5);
        FieldNum.setValue(1);
        FieldNum.setValue(0);
        FieldNum.setValue(1);
        DeviceCount.setValue(1);
        TKN.setValue(10);

    }

    public ArrayList<Key> Klist = new ArrayList<>();

    public void Kgeneretor() {
        String temp = "";

        /*
        String digits = "0123456789";
        String lowers = "abcdefghijklmnopqrstuvwxyz";
        String uppers = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String symbols = "!@#$%^&*()";
         */
        String total = AllowedSymbolsBox.getText();

        ArrayList<Character> AllowedCharacters = new ArrayList<>();

        for (int i = 0; i < total.length(); i++) {
            AllowedCharacters.add(total.charAt(i));
        }

        for (int k = 0; k < TotalKeyNumber; k++) {
            Klist.add(new Key());

            for (int j = 0; j < FieldNumber; j++) {

                for (int i = 0; i < SymbolNumber; i++) {
                    int rand = (int) (AllowedCharacters.size() * Math.random());
                    temp += String.valueOf(AllowedCharacters.get(rand));

                }
                if ((FieldNumber > 1) && (FieldNumber != (j + 1))) {
                    temp += "-";
                }

            }
            Klist.get(k).setCode(temp);
            temp = "";
        }

        for (int i = 0; i < Klist.size(); i++) {
            System.out.println("AAA: " + Klist.get(i).getCode());
            Klist.get(i).setDevices((int) DeviceCount.getValue());
        }
        System.out.println("ended");
    }

    private int Xdays;

    public String DateCalc() {

        Date d2 = EndingDateChooser.getDate();
        Date d1 = StartingDateChooser.getDate();

        for (int i = 0; i < Klist.size(); i++) {
            Klist.get(i).setStartingDate(d1);
            Klist.get(i).setExpDate(d2);
        }

        long diff = d2.getTime() - d1.getTime();

        Xdays = (int) (diff / (1000 * 60 * 60 * 24));

        System.out.println("Difference between  " + d1 + " and " + d2 + " is "
                + (diff / (1000 * 60 * 60 * 24)) + " days.");

        return (diff / (1000 * 60 * 60 * 24)) + " days.";

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        Form1 = new javax.swing.JPanel();
        Title1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        SerialPanel = new javax.swing.JPanel();
        Serial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PathMessage1 = new javax.swing.JLabel();
        SymbolNum = new javax.swing.JSpinner();
        FieldNum = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DeviceCount = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TKN = new javax.swing.JSpinner();
        EndingDateChooser = new com.toedter.calendar.JDateChooser();
        StartingDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        UnilimtedCheckB = new javax.swing.JCheckBox();
        Confirm1 = new javax.swing.JButton();
        AllowedSymbolsPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        AllowedSymbolsBox = new javax.swing.JTextField();
        NumbersCheckB = new javax.swing.JCheckBox();
        SmallLettersCheckB = new javax.swing.JCheckBox();
        SymbolsCheckB = new javax.swing.JCheckBox();
        CapitalLettersCheckB = new javax.swing.JCheckBox();
        SpaceCheckB = new javax.swing.JCheckBox();
        SerialCodeCorrect = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        Form2 = new javax.swing.JPanel();
        Title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Fpath = new javax.swing.JPanel();
        PathArea = new javax.swing.JTextField();
        OpenPath = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PathMessage = new javax.swing.JLabel();
        Confirm = new javax.swing.JButton();
        SelectPath1 = new javax.swing.JButton();
        SelectPath = new javax.swing.JButton();
        FilePathCorrect = new javax.swing.JButton();
        Operation = new javax.swing.JPanel();
        CreateButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        ReadButton = new javax.swing.JButton();
        BottomMessages = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        Form3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        pnlRoot.setBackground(new java.awt.Color(22, 22, 22));
        pnlRoot.setLayout(new java.awt.BorderLayout());

        jTabbedPane.setBackground(new java.awt.Color(21, 25, 28));
        jTabbedPane.setForeground(new java.awt.Color(102, 204, 255));
        jTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane.setToolTipText("");
        jTabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTabbedPane.setPreferredSize(new java.awt.Dimension(200, 200));
        jTabbedPane.setRequestFocusEnabled(false);

        Form1.setBackground(new java.awt.Color(34, 40, 44));
        Form1.setPreferredSize(new java.awt.Dimension(100, 100));

        Title1.setBackground(new java.awt.Color(34, 40, 44));
        Title1.setToolTipText("");
        Title1.setPreferredSize(new java.awt.Dimension(1000, 100));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Serial Code Modification");

        javax.swing.GroupLayout Title1Layout = new javax.swing.GroupLayout(Title1);
        Title1.setLayout(Title1Layout);
        Title1Layout.setHorizontalGroup(
            Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Title1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(547, Short.MAX_VALUE))
        );
        Title1Layout.setVerticalGroup(
            Title1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Title1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        SerialPanel.setBackground(new java.awt.Color(34, 40, 44));
        SerialPanel.setToolTipText("");
        SerialPanel.setPreferredSize(new java.awt.Dimension(1000, 100));

        Serial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Serial.setText("XXXXX");
        Serial.setPreferredSize(new java.awt.Dimension(300, 22));
        Serial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerialActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Serial Code:");

        PathMessage1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PathMessage1.setForeground(new java.awt.Color(255, 51, 51));

        SymbolNum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SymbolNumStateChanged(evt);
            }
        });

        FieldNum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                FieldNumStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Fields Number:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Symbols Number:");

        DeviceCount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DeviceCountStateChanged(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Devices Number:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Expiry Date:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Total Keys Number:");

        TKN.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TKNStateChanged(evt);
            }
        });

        EndingDateChooser.setBackground(new java.awt.Color(34, 40, 44));
        EndingDateChooser.setForeground(new java.awt.Color(0, 255, 204));
        EndingDateChooser.setDateFormatString("dd MM, yyyy");
        EndingDateChooser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EndingDateChooser.setIcon(null);

        StartingDateChooser.setBackground(new java.awt.Color(34, 40, 44));
        StartingDateChooser.setForeground(new java.awt.Color(0, 255, 204));
        StartingDateChooser.setDateFormatString("dd MM, yyyy");
        StartingDateChooser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StartingDateChooser.setIcon(null);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Starting Date:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Ending Date:");

        UnilimtedCheckB.setText("Unlimted Activision");
        UnilimtedCheckB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnilimtedCheckBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SerialPanelLayout = new javax.swing.GroupLayout(SerialPanel);
        SerialPanel.setLayout(SerialPanelLayout);
        SerialPanelLayout.setHorizontalGroup(
            SerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SerialPanelLayout.createSequentialGroup()
                .addGroup(SerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SerialPanelLayout.createSequentialGroup()
                        .addGap(576, 576, 576)
                        .addComponent(PathMessage1))
                    .addGroup(SerialPanelLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(SerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SerialPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addGroup(SerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(SerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(SerialPanelLayout.createSequentialGroup()
                                        .addComponent(FieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(DeviceCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(SerialPanelLayout.createSequentialGroup()
                                        .addComponent(SymbolNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TKN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(SerialPanelLayout.createSequentialGroup()
                                .addComponent(Serial, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UnilimtedCheckB))
                            .addGroup(SerialPanelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(StartingDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel17)
                                .addGap(12, 12, 12)
                                .addComponent(EndingDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        SerialPanelLayout.setVerticalGroup(
            SerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SerialPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PathMessage1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(SerialPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(SerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(SymbolNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TKN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FieldNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(DeviceCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Serial, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UnilimtedCheckB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SerialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(StartingDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addComponent(EndingDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        Confirm1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Confirm1.setText("Confirm");
        Confirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm1ActionPerformed(evt);
            }
        });

        AllowedSymbolsPanel.setBackground(new java.awt.Color(34, 40, 44));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Allowed Symbols:");

        AllowedSymbolsBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AllowedSymbolsBox.setText("0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()");
        AllowedSymbolsBox.setPreferredSize(new java.awt.Dimension(300, 22));
        AllowedSymbolsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllowedSymbolsBoxActionPerformed(evt);
            }
        });

        NumbersCheckB.setSelected(true);
        NumbersCheckB.setText("Numbers");
        NumbersCheckB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumbersCheckBActionPerformed(evt);
            }
        });

        SmallLettersCheckB.setSelected(true);
        SmallLettersCheckB.setText("Small Letters");
        SmallLettersCheckB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmallLettersCheckBActionPerformed(evt);
            }
        });

        SymbolsCheckB.setSelected(true);
        SymbolsCheckB.setText("Symbols");
        SymbolsCheckB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SymbolsCheckBActionPerformed(evt);
            }
        });

        CapitalLettersCheckB.setSelected(true);
        CapitalLettersCheckB.setText("Capital Letters");
        CapitalLettersCheckB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapitalLettersCheckBActionPerformed(evt);
            }
        });

        SpaceCheckB.setText("Space");
        SpaceCheckB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpaceCheckBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AllowedSymbolsPanelLayout = new javax.swing.GroupLayout(AllowedSymbolsPanel);
        AllowedSymbolsPanel.setLayout(AllowedSymbolsPanelLayout);
        AllowedSymbolsPanelLayout.setHorizontalGroup(
            AllowedSymbolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllowedSymbolsPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(AllowedSymbolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AllowedSymbolsPanelLayout.createSequentialGroup()
                        .addComponent(NumbersCheckB)
                        .addGap(18, 18, 18)
                        .addComponent(SmallLettersCheckB)
                        .addGap(18, 18, 18)
                        .addComponent(CapitalLettersCheckB)
                        .addGap(18, 18, 18)
                        .addComponent(SymbolsCheckB)
                        .addGap(18, 18, 18)
                        .addComponent(SpaceCheckB))
                    .addComponent(jLabel20)
                    .addComponent(AllowedSymbolsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AllowedSymbolsPanelLayout.setVerticalGroup(
            AllowedSymbolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AllowedSymbolsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(AllowedSymbolsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AllowedSymbolsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumbersCheckB)
                    .addComponent(SmallLettersCheckB)
                    .addComponent(SymbolsCheckB)
                    .addComponent(CapitalLettersCheckB)
                    .addComponent(SpaceCheckB))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        SerialCodeCorrect.setBackground(new java.awt.Color(34, 40, 44));
        SerialCodeCorrect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_in_progress_30px.png"))); // NOI18N
        SerialCodeCorrect.setAlignmentX(0.5F);
        SerialCodeCorrect.setBorderPainted(false);
        SerialCodeCorrect.setContentAreaFilled(false);
        SerialCodeCorrect.setDefaultCapable(false);
        SerialCodeCorrect.setFocusPainted(false);
        SerialCodeCorrect.setFocusable(false);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(34, 40, 44));
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("⋆ After finishing and clicking on Confirm button at the end please go to Excel Modify section.");
        jTextArea4.setFocusable(false);
        jScrollPane5.setViewportView(jTextArea4);

        javax.swing.GroupLayout Form1Layout = new javax.swing.GroupLayout(Form1);
        Form1.setLayout(Form1Layout);
        Form1Layout.setHorizontalGroup(
            Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Form1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(Form1Layout.createSequentialGroup()
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SerialPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AllowedSymbolsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Form1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Form1Layout.createSequentialGroup()
                                .addComponent(Confirm1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SerialCodeCorrect)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Form1Layout.setVerticalGroup(
            Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Form1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AllowedSymbolsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SerialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Confirm1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SerialCodeCorrect))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("   Serial Code", Form1);

        Form2.setBackground(new java.awt.Color(34, 40, 44));
        Form2.setPreferredSize(new java.awt.Dimension(50, 100));

        Title.setBackground(new java.awt.Color(34, 40, 44));
        Title.setToolTipText("");
        Title.setPreferredSize(new java.awt.Dimension(1000, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Excel File Modification");

        javax.swing.GroupLayout TitleLayout = new javax.swing.GroupLayout(Title);
        Title.setLayout(TitleLayout);
        TitleLayout.setHorizontalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitleLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(547, Short.MAX_VALUE))
        );
        TitleLayout.setVerticalGroup(
            TitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitleLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        Fpath.setBackground(new java.awt.Color(34, 40, 44));
        Fpath.setToolTipText("");
        Fpath.setPreferredSize(new java.awt.Dimension(1000, 100));

        PathArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PathArea.setText("List.xlsx");
        PathArea.setPreferredSize(new java.awt.Dimension(300, 22));
        PathArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PathAreaActionPerformed(evt);
            }
        });

        OpenPath.setText("Open File");
        OpenPath.setPreferredSize(new java.awt.Dimension(100, 22));
        OpenPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenPathActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("File Path:");

        PathMessage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PathMessage.setForeground(new java.awt.Color(255, 51, 51));

        Confirm.setBackground(new java.awt.Color(51, 102, 0));
        Confirm.setText("Confirm");
        Confirm.setPreferredSize(new java.awt.Dimension(100, 22));
        Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmActionPerformed(evt);
            }
        });

        SelectPath1.setText("Create File");
        SelectPath1.setPreferredSize(new java.awt.Dimension(100, 22));
        SelectPath1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectPath1ActionPerformed(evt);
            }
        });

        SelectPath.setText("Select File");
        SelectPath.setPreferredSize(new java.awt.Dimension(100, 22));
        SelectPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectPathActionPerformed(evt);
            }
        });

        FilePathCorrect.setBackground(new java.awt.Color(34, 40, 44));
        FilePathCorrect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_in_progress_30px.png"))); // NOI18N
        FilePathCorrect.setAlignmentX(0.5F);
        FilePathCorrect.setBorderPainted(false);
        FilePathCorrect.setContentAreaFilled(false);
        FilePathCorrect.setDefaultCapable(false);
        FilePathCorrect.setFocusPainted(false);
        FilePathCorrect.setFocusable(false);

        javax.swing.GroupLayout FpathLayout = new javax.swing.GroupLayout(Fpath);
        Fpath.setLayout(FpathLayout);
        FpathLayout.setHorizontalGroup(
            FpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FpathLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(FpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FpathLayout.createSequentialGroup()
                        .addComponent(Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OpenPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelectPath1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelectPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FpathLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addGroup(FpathLayout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(FilePathCorrect))
                    .addGroup(FpathLayout.createSequentialGroup()
                        .addComponent(PathArea, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PathMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        FpathLayout.setVerticalGroup(
            FpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FpathLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(FpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PathMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PathArea, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(FpathLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Confirm, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(OpenPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SelectPath1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SelectPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(FpathLayout.createSequentialGroup()
                .addComponent(FilePathCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Operation.setBackground(new java.awt.Color(34, 40, 44));
        Operation.setToolTipText("");
        Operation.setPreferredSize(new java.awt.Dimension(1000, 100));

        CreateButton.setBackground(new java.awt.Color(0, 102, 102));
        CreateButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        CreateButton.setForeground(new java.awt.Color(255, 255, 255));
        CreateButton.setText("Create");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Operation:");

        UpdateButton.setBackground(new java.awt.Color(0, 102, 51));
        UpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        ReadButton.setBackground(new java.awt.Color(102, 0, 0));
        ReadButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ReadButton.setForeground(new java.awt.Color(255, 255, 255));
        ReadButton.setText("Read");
        ReadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OperationLayout = new javax.swing.GroupLayout(Operation);
        Operation.setLayout(OperationLayout);
        OperationLayout.setHorizontalGroup(
            OperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperationLayout.createSequentialGroup()
                .addGroup(OperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OperationLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel3))
                    .addGroup(OperationLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(CreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ReadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(448, Short.MAX_VALUE))
        );
        OperationLayout.setVerticalGroup(
            OperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperationLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateButton))
                .addGap(0, 41, Short.MAX_VALUE))
        );

        BottomMessages.setPreferredSize(new java.awt.Dimension(1000, 200));

        jLabel4.setText("●  Create Button: ");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("This button creates an empty excel file in the\nthe location you chose above (in File Path).");
        jTextArea1.setBorder(null);
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setText("●  Update Button: ");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("This button updates the file and adds the new serial codes\nto the excel file without losing any old serial codes.");
        jTextArea2.setBorder(null);
        jTextArea2.setFocusable(false);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel6.setText("●  Read Button: ");

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("This button reads all serial codes to see which one has expired.");
        jTextArea3.setBorder(null);
        jTextArea3.setFocusable(false);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel7.setText("⋆ If you are new to this program: first press Create button then make a serial code through the Home section in the side menu and click update.");

        javax.swing.GroupLayout BottomMessagesLayout = new javax.swing.GroupLayout(BottomMessages);
        BottomMessages.setLayout(BottomMessagesLayout);
        BottomMessagesLayout.setHorizontalGroup(
            BottomMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomMessagesLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(BottomMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
                    .addGroup(BottomMessagesLayout.createSequentialGroup()
                        .addGroup(BottomMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addContainerGap())))
        );
        BottomMessagesLayout.setVerticalGroup(
            BottomMessagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomMessagesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Form2Layout = new javax.swing.GroupLayout(Form2);
        Form2.setLayout(Form2Layout);
        Form2Layout.setHorizontalGroup(
            Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Form2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Operation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(BottomMessages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Form2Layout.setVerticalGroup(
            Form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Form2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fpath, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Operation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BottomMessages, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("   Excel Modify", Form2);

        Form3.setBackground(new java.awt.Color(34, 40, 44));
        Form3.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Serial Code Modification");
        jLabel10.setDisplayedMnemonicIndex(1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Starting Date", "Ending Date", "Devices", "Status"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jLabel19.setText("⋆ If you see this table empty you need to press the Read button in Excel Modify section.");

        javax.swing.GroupLayout Form3Layout = new javax.swing.GroupLayout(Form3);
        Form3.setLayout(Form3Layout);
        Form3Layout.setHorizontalGroup(
            Form3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Form3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 225, Short.MAX_VALUE))
            .addGroup(Form3Layout.createSequentialGroup()
                .addGroup(Form3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Form3Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Form3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Form3Layout.setVerticalGroup(
            Form3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Form3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("            Expiry", Form3);

        pnlRoot.add(jTabbedPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ReadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadButtonActionPerformed

        if (Filepath == null) {
            PathMessage.setText("File path is empty please press confirm button.");

        } else {
            try {
                ReadingList = excel.ExcelReader(Filepath, Unlimited);
                PathMessage.setText(null);

            } catch (Exception ex) {

                PathMessage.setText("File path is wrong");
            }
        }

        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        String arr[] = new String[5];

        for (int i = 0; i < ReadingList.size(); i++) {

            SimpleDateFormat DateFormat1 = new SimpleDateFormat("yy/MM/dd");
            SimpleDateFormat DateFormat2 = new SimpleDateFormat("yy/MM/dd");

            String curr_date1 = DateFormat1.format(ReadingList.get(i).getStartingDate().getTime());

            if (ReadingList.get(i).getExpDate() != null) {
                String curr_date2 = DateFormat2.format(ReadingList.get(i).getExpDate().getTime());

                arr[0] = ReadingList.get(i).getCode();
                arr[1] = curr_date1;
                arr[2] = curr_date2;
                arr[3] = ReadingList.get(i).getDevices() + "";
                arr[4] = ReadingList.get(i).getStatus();

                tblModel.addRow(arr);
            } else {
                String curr_date2 = "Unlimited";

                arr[0] = ReadingList.get(i).getCode();
                arr[1] = curr_date1;
                arr[2] = curr_date2;
                arr[3] = ReadingList.get(i).getDevices() + "";
                arr[4] = ReadingList.get(i).getStatus();

                tblModel.addRow(arr);
            }

        }

        TableColumn tColumn;
        tColumn = jTable1.getColumnModel().getColumn(4);
        tColumn.setCellRenderer(new ColumnColorRenderer(Color.DARK_GRAY, Color.getHSBColor(10, 100, 57)));

        JOptionPane.showMessageDialog(null, "Now you can go to Expiry section.");
    }//GEN-LAST:event_ReadButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        if (Filepath == null) {
            PathMessage.setText("File path is empty please press confirm button.");

        } else {
            try {
                excel.ExcelUpdate(Filepath, Klist, Unlimited);
                PathMessage.setText(null);
                JOptionPane.showMessageDialog(null, "Updated Successfully.");

            } catch (Exception ex) {

                PathMessage.setText("File path is wrong");
            }

            System.out.println("GIGA");
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed

        if (Filepath == null) {
            PathMessage.setText("File path is empty please press confirm button.");

        } else {
            try {
                excel.ExcelWrite(Filepath);
                PathMessage.setText(null);

            } catch (IOException ex) {

                PathMessage.setText("File path is wrong");
            }
        }
    }//GEN-LAST:event_CreateButtonActionPerformed

    private void SelectPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectPathActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setAcceptAllFileFilterUsed(false);
        FileFilter filter = new FileNameExtensionFilter("Excel file", "xls", "xlsx");
        fileChooser.addChoosableFileFilter(filter);

        fileChooser.setCurrentDirectory(new File("."));
        int resp = fileChooser.showOpenDialog(null); // response

        if (resp != 1) {
            File f = fileChooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            System.out.println(filename);

            PathArea.setText(filename);

        }
    }//GEN-LAST:event_SelectPathActionPerformed

    private void SelectPath1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectPath1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("."));
        int resp = fileChooser.showSaveDialog(null); // response

        if (resp != 1) {
            File f = fileChooser.getSelectedFile();
            String filename = f.getAbsolutePath();
            System.out.println(filename + ".xlsx");

            PathArea.setText(filename + ".xlsx");

        }
    }//GEN-LAST:event_SelectPath1ActionPerformed

    private void ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmActionPerformed
        Filepath = PathArea.getText();
        FilePathCorrect.setVisible(true);
        PathMessage.setText(null);
    }//GEN-LAST:event_ConfirmActionPerformed

    private void OpenPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenPathActionPerformed

        Desktop desktop = Desktop.getDesktop();
        File dirToOpen = null;
        try {
            String path = PathArea.getText();
            Runtime runtime = Runtime.getRuntime();
            runtime.exec("explorer.exe " + path);
            System.out.println("File explorer opened");
        } catch (Exception E) {
            System.out.println("File Not Found for File explorer");
        }
    }//GEN-LAST:event_OpenPathActionPerformed

    private void PathAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PathAreaActionPerformed

    }//GEN-LAST:event_PathAreaActionPerformed

    private void SpaceCheckBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpaceCheckBActionPerformed
        if (!SpaceCheckB.isSelected()) {

            String Stemp = AllowedSymbolsBox.getText();
            /// TAL HANAN // Pegasus for hacking devices
            String strNew = Stemp.replace(" ", "");
            AllowedSymbolsBox.setText(strNew);

        } else {
            String Stemp = AllowedSymbolsBox.getText();
            Stemp = Stemp + " ";
            AllowedSymbolsBox.setText(Stemp);
        }
    }//GEN-LAST:event_SpaceCheckBActionPerformed

    private void CapitalLettersCheckBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapitalLettersCheckBActionPerformed
        if (!CapitalLettersCheckB.isSelected()) {

            String Stemp = AllowedSymbolsBox.getText();
            /// TAL HANAN // Pegasus for hacking devices
            String strNew = Stemp.replace("ABCDEFGHIJKLMNOPQRSTUVWXYZ", "");
            AllowedSymbolsBox.setText(strNew);

        } else {
            String Stemp = AllowedSymbolsBox.getText();
            Stemp = Stemp + "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            AllowedSymbolsBox.setText(Stemp);
        }
    }//GEN-LAST:event_CapitalLettersCheckBActionPerformed

    private void SymbolsCheckBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SymbolsCheckBActionPerformed
        if (!SymbolsCheckB.isSelected()) {

            String Stemp = AllowedSymbolsBox.getText();
            /// TAL HANAN // Pegasus for hacking devices
            String strNew = Stemp.replace("!@#$%^&*()", "");
            AllowedSymbolsBox.setText(strNew);

        } else {
            String Stemp = AllowedSymbolsBox.getText();
            Stemp = Stemp + "!@#$%^&*()";
            AllowedSymbolsBox.setText(Stemp);
        }
    }//GEN-LAST:event_SymbolsCheckBActionPerformed

    private void SmallLettersCheckBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmallLettersCheckBActionPerformed
        if (!SmallLettersCheckB.isSelected()) {

            String Stemp = AllowedSymbolsBox.getText();
            /// TAL HANAN // Pegasus for hacking devices
            String strNew = Stemp.replace("abcdefghijklmnopqrstuvwxyz", "");
            AllowedSymbolsBox.setText(strNew);

        } else {
            String Stemp = AllowedSymbolsBox.getText();
            Stemp = Stemp + "abcdefghijklmnopqrstuvwxyz";
            AllowedSymbolsBox.setText(Stemp);
        }
    }//GEN-LAST:event_SmallLettersCheckBActionPerformed

    private void NumbersCheckBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumbersCheckBActionPerformed
        if (!NumbersCheckB.isSelected()) {

            String Stemp = AllowedSymbolsBox.getText();
            /// TAL HANAN // Pegasus for hacking devices
            String strNew = Stemp.replace("0123456789", "");
            AllowedSymbolsBox.setText(strNew);

        } else {
            String Stemp = AllowedSymbolsBox.getText();
            Stemp = Stemp + "0123456789";
            AllowedSymbolsBox.setText(Stemp);
        }
    }//GEN-LAST:event_NumbersCheckBActionPerformed

    private void AllowedSymbolsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllowedSymbolsBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AllowedSymbolsBoxActionPerformed

    private void Confirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm1ActionPerformed

        Klist.clear();

        if ((AllowedSymbolsBox.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Please select the allowed symbols.");
            return;
        }

        if ((StartingDateChooser.getDate() == null) && !(UnilimtedCheckB.isSelected())) {
            JOptionPane.showMessageDialog(null, "Please select the expiration date.");
        } else {
            Kgeneretor();
            if (!UnilimtedCheckB.isSelected()) {

                jLabel18.setText(DateCalc());

                if ((Xdays <= 0) && !(UnilimtedCheckB.isSelected())) {
                    JOptionPane.showMessageDialog(null, "Date is invalid. (" + Xdays + " days.)");
                } else {
                    JOptionPane.showMessageDialog(null, "You can go to excel section.");
                    SerialCodeCorrect.setVisible(true);
                }
            } else { // Unlimited Activision
                Unlimited = true;
                JOptionPane.showMessageDialog(null, "You can go to excel section.");
                SerialCodeCorrect.setVisible(true);
            }
        }
    }//GEN-LAST:event_Confirm1ActionPerformed

    private void UnilimtedCheckBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnilimtedCheckBActionPerformed

        if (UnilimtedCheckB.isSelected()) {
            StartingDateChooser.setEnabled(false);
            EndingDateChooser.setEnabled(false);
        } else {
            StartingDateChooser.setEnabled(true);
            EndingDateChooser.setEnabled(true);
        }
    }//GEN-LAST:event_UnilimtedCheckBActionPerformed

    private void TKNStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TKNStateChanged
        TotalKeyNumber = (int) TKN.getValue();
    }//GEN-LAST:event_TKNStateChanged

    private void DeviceCountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DeviceCountStateChanged
        DeviceCounter = (int) DeviceCount.getValue();
    }//GEN-LAST:event_DeviceCountStateChanged

    private void FieldNumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FieldNumStateChanged

        SCexample = "X";
        for (int j = 0; j < (int) FieldNum.getValue(); j++) {

            for (int i = 0; i < (int) SymbolNum.getValue(); i++) {
                SCexample = SCexample + "X";
            }
            if ((FieldNumber > 0) && (FieldNumber != (j))) {
                SCexample = SCexample + "-";
            }
        }

        SCexample = SCexample.substring(1);

        FieldNumber = (int) FieldNum.getValue();
        Serial.setText(SCexample);
    }//GEN-LAST:event_FieldNumStateChanged

    private void SymbolNumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SymbolNumStateChanged

        SCexample = "X";
        for (int j = 0; j < (int) FieldNum.getValue(); j++) {
            for (int i = 0; i < (int) SymbolNum.getValue(); i++) {
                SCexample = SCexample + "X";
            }
            if ((FieldNumber > 1) && (FieldNumber != (j + 1))) {
                SCexample = SCexample + "-";
            }
        }

        SCexample = SCexample.substring(1);

        SymbolNumber = (int) SymbolNum.getValue();
        Serial.setText(SCexample);
    }//GEN-LAST:event_SymbolNumStateChanged

    private void SerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SerialActionPerformed

    public String Filepath;
    public Excel excel = new Excel();
    public JLayeredPane layeredPane = new JLayeredPane();
    public int SymbolNumber = 5;
    public int FieldNumber = 1;
    public String SCexample;
    public int DeviceCounter = 1;
    public int TotalKeyNumber = 10;


    private boolean Unlimited = false;

    private ArrayList<Key> ReadingList;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AllowedSymbolsBox;
    private javax.swing.JPanel AllowedSymbolsPanel;
    private javax.swing.JPanel BottomMessages;
    private javax.swing.JCheckBox CapitalLettersCheckB;
    private javax.swing.JButton Confirm;
    private javax.swing.JButton Confirm1;
    private javax.swing.JButton CreateButton;
    private javax.swing.JSpinner DeviceCount;
    private com.toedter.calendar.JDateChooser EndingDateChooser;
    private javax.swing.JSpinner FieldNum;
    private javax.swing.JButton FilePathCorrect;
    private javax.swing.JPanel Form1;
    private javax.swing.JPanel Form2;
    private javax.swing.JPanel Form3;
    private javax.swing.JPanel Fpath;
    private javax.swing.JCheckBox NumbersCheckB;
    private javax.swing.JButton OpenPath;
    private javax.swing.JPanel Operation;
    private javax.swing.JTextField PathArea;
    private javax.swing.JLabel PathMessage;
    private javax.swing.JLabel PathMessage1;
    private javax.swing.JButton ReadButton;
    private javax.swing.JButton SelectPath;
    private javax.swing.JButton SelectPath1;
    private javax.swing.JTextField Serial;
    private javax.swing.JButton SerialCodeCorrect;
    private javax.swing.JPanel SerialPanel;
    private javax.swing.JCheckBox SmallLettersCheckB;
    private javax.swing.JCheckBox SpaceCheckB;
    private com.toedter.calendar.JDateChooser StartingDateChooser;
    private javax.swing.JSpinner SymbolNum;
    private javax.swing.JCheckBox SymbolsCheckB;
    private javax.swing.JSpinner TKN;
    private javax.swing.JPanel Title;
    private javax.swing.JPanel Title1;
    private javax.swing.JCheckBox UnilimtedCheckB;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JPanel pnlRoot;
    // End of variables declaration//GEN-END:variables
}
